#include "table.h"

#include <algorithm>
#include <set>
#include <sstream>

#include "../log/log.h"
#include "../util/string_util.h"
#include "../util/util.h" // IWYU pragma: keep
#include "util.h"

namespace chen {
namespace orm {

static Logger::ptr logger = LOG_NAME("orm");

bool Table::init(const tinyxml2::XMLElement& node) {
    if (!node.Attribute("name")) {
        ERROR(logger) << "table name is null";
        return false;
    }

    m_name = node.Attribute("name");
    if (!node.Attribute("namespace")) {
        ERROR(logger) << "table namespace is null";
        return false;
    }
    m_namespace = node.Attribute("namespace");

    if (node.Attribute("desc")) {
        m_desc = node.Attribute("desc");
    }

    if (node.Attribute("version")) {
        m_version = node.IntAttribute("version");
    }

    const tinyxml2::XMLElement* cols = node.FirstChildElement("columns");
    if (!cols) {
        ERROR(logger) << "table name=" << m_name << " columns is null";
        return false;
    }

    const tinyxml2::XMLElement* col = cols->FirstChildElement("column");
    if (!col) {
        ERROR(logger) << "table name=" << m_name << " colmun is null";
        return false;
    }

    std::set<std::string> col_names;
    int index = 0;
    do {
        Column::ptr col_ptr(new Column);
        if (!col_ptr->init(*col)) {
            ERROR(logger) << "table name=" << m_name << " init column error";
            return false;
        }
        if (col_names.insert(col_ptr->getName()).second == false) {
            ERROR(logger) << "table name=" << m_name << " column name=" << col_ptr->getName() << " exists";
            return false;
        }
        col_ptr->m_index = index++;
        m_cols.push_back(col_ptr);
        col = col->NextSiblingElement("column");
    } while (col);

    const tinyxml2::XMLElement* idxs = node.FirstChildElement("indexs");
    if (!idxs) {
        ERROR(logger) << "table name=" << m_name << " index is null";
        return false;
    }

    const tinyxml2::XMLElement* idx = idxs->FirstChildElement("index");
    if (!idx) {
        ERROR(logger) << "table name=" << m_name << " index is null";
        return false;
    }

    std::set<std::string> idx_names;
    bool has_pk = false;
    do {
        Index::ptr idx_ptr(new Index);
        if (!idx_ptr->init(*idx)) {
            ERROR(logger) << "table name=" << m_name << " index init error";
            return false;
        }
        if (idx_names.insert(idx_ptr->getName()).second == false) {
            ERROR(logger) << "table name=" << m_name << " index name=" << idx_ptr->getName() << " exists";
            return false;
        }
        if (idx_ptr->isPK()) {
            if (has_pk) {
                ERROR(logger) << "table name=" << m_name << " more than one pk";
                return false;
            }
            has_pk = true;
        }

        auto& cnames = idx_ptr->getCols();
        for (auto& x : cnames) {
            if (col_names.count(x) == 0) {
                ERROR(logger) << "table name=" << m_name << " idx=" << idx_ptr->getName() << " col=" << x << " not exists";
                return false;
            }
        }

        m_idxs.push_back(idx_ptr);
        idx = idx->NextSiblingElement("index");
    } while (idx);
    return true;
}

void Table::gen(const std::string& path) {
    std::string p = path + "/" + StringUtil::Replace(m_namespace, ".", "/");
    FSUtil::Mkdir(p);
    gen_inc(p);
    gen_src(p);
}

std::string Table::getFileName() const {
    std::string str = m_name + m_subfix;
    std::transform(str.begin(), str.end(), str.begin(), ::tolower);
    return str;
}

void Table::gen_inc(const std::string& path) {
    std::string filename = path + "/" + m_name + m_subfix + ".h";
    std::string class_name = m_name + m_subfix;
    std::string class_name_dao = m_name + m_subfix + "_dao";
    std::ofstream ofs(filename);
    ofs << "/**" << std::endl;
    ofs << " * @file " << class_name << ".h" << std::endl;
    if (!m_desc.empty()) {
        ofs << " * @brief " << m_desc << std::endl;
    }
    ofs << " * @note Auto-generated by ORM code generator. DO NOT MODIFY." << std::endl;
    ofs << " */" << std::endl;
    ofs << "#pragma once" << std::endl;
    ofs << std::endl;

    std::set<std::string> sincs = {"vector"};
    for (auto& i : sincs) {
        ofs << "#include <" << i << ">" << std::endl;
    }
    ofs << std::endl;

    std::set<std::string> incs = {"<chen/db/db.h>", "<chen/db/query_builder.h>", "<chen/util/util.h>"};
    for (auto& i : incs) {
        ofs << "#include " << i << std::endl;
    }
    ofs << std::endl;

    std::vector<std::string> ns = StringUtil::Split(m_namespace, '.', false);
    for (auto it = ns.begin(); it != ns.end(); ++it) {
        ofs << "namespace " << *it << " {" << std::endl;
    }

    ofs << std::endl;
    ofs << "class " << GetAsClassName(class_name_dao) << ";" << std::endl;
    if (!m_desc.empty()) {
        ofs << "/**" << std::endl;
        ofs << " * @brief " << m_desc << std::endl;
        ofs << " */" << std::endl;
    }
    ofs << "class " << GetAsClassName(class_name) << " {" << std::endl;
    ofs << "friend class " << GetAsClassName(class_name_dao) << ";" << std::endl;
    ofs << "public:" << std::endl;
    ofs << "    typedef std::shared_ptr<" << GetAsClassName(class_name) << "> ptr;" << std::endl;
    ofs << std::endl;
    ofs << "    " << GetAsClassName(class_name) << "();" << std::endl;
    ofs << std::endl;

    auto cols = m_cols;
    std::sort(cols.begin(), cols.end(), [](const Column::ptr& a, const Column::ptr& b) {
        if (a->getDType() != b->getDType()) {
            return a->getDType() < b->getDType();
        } else {
            return a->getIndex() < b->getIndex();
        }
    });

    for (auto& i : m_cols) {
        ofs << "    " << i->getGetFunDefine();
        ofs << "    " << i->getSetFunDefine();
        ofs << std::endl;
    }
    ofs << "    /**" << std::endl;
    ofs << "     * @brief 转为 JSON 字符串" << std::endl;
    ofs << "     * @return JSON 字符串" << std::endl;
    ofs << "     */" << std::endl;
    ofs << "    " << genToStringInc() << std::endl;
    ofs << std::endl;
    ofs << "    /** @brief 清除脏标记（Update 成功后自动调用） */" << std::endl;
    ofs << "    void markClean() { m_flags = 0; }" << std::endl;
    ofs << "    /**" << std::endl;
    ofs << "     * @brief 是否有字段被修改过" << std::endl;
    ofs << "     * @return true 有未保存的修改，false 无修改" << std::endl;
    ofs << "     */" << std::endl;
    ofs << "    bool isDirty() const { return m_flags != 0; }" << std::endl;
    // ofs << "    std::string toInsertSQL() const;" << std::endl;
    // ofs << "    std::string toUpdateSQL() const;" << std::endl;
    // ofs << "    std::string toDeleteSQL() const;" << std::endl;
    ofs << std::endl;

    ofs << "private:" << std::endl;
    for (auto& i : cols) {
        ofs << "    " << i->getMemberDefine();
    }
    ofs << "    uint64_t m_flags = 0;" << std::endl;
    ofs << "};" << std::endl;
    ofs << std::endl;

    ofs << std::endl;
    gen_dao_inc(ofs);
    ofs << std::endl;

    for (auto it = ns.rbegin(); it != ns.rend(); ++it) {
        ofs << "} //namespace " << *it << std::endl;
    }
}

void Table::gen_src(const std::string& path) {
    std::string class_name = m_name + m_subfix;
    std::string filename = path + "/" + class_name + ".cc";
    std::ofstream ofs(filename);

    ofs << "/**" << std::endl;
    ofs << " * @file " << class_name << ".cc" << std::endl;
    if (!m_desc.empty()) {
        ofs << " * @brief " << m_desc << std::endl;
    }
    ofs << " * @note Auto-generated by ORM code generator. DO NOT MODIFY." << std::endl;
    ofs << " */" << std::endl;
    ofs << "#include \"" << class_name + ".h\"" << std::endl;
    ofs << std::endl;
    ofs << "#include <chen/log/log.h>" << std::endl;
    ofs << std::endl;
    ofs << "#include <map>" << std::endl;
    ofs << std::endl;

    std::vector<std::string> ns = StringUtil::Split(m_namespace, '.', false);
    for (auto it = ns.begin(); it != ns.end(); ++it) {
        ofs << "namespace " << *it << " {" << std::endl;
    }

    ofs << std::endl;
    ofs << "static chen::Logger::ptr logger = LOG_NAME(\"orm\");" << std::endl;

    ofs << std::endl;
    ofs << GetAsClassName(class_name) << "::" << GetAsClassName(class_name) << "()" << std::endl;
    ofs << "    :";
    auto cols = m_cols;
    std::sort(cols.begin(), cols.end(), [](const Column::ptr& a, const Column::ptr& b) {
        if (a->getDType() != b->getDType()) {
            return a->getDType() < b->getDType();
        } else {
            return a->getIndex() < b->getIndex();
        }
    });
    for (auto it = cols.begin(); it != cols.end(); ++it) {
        if (it != cols.begin()) {
            ofs << std::endl << "    ,";
        }
        ofs << GetAsMemberName((*it)->getName()) << "(" << (*it)->getDefaultValueString() << ")";
    }
    ofs << " {" << std::endl;
    ofs << "}" << std::endl;
    ofs << std::endl;

    ofs << genToStringSrc(class_name) << std::endl;

    for (size_t i = 0; i < m_cols.size(); ++i) {
        ofs << m_cols[i]->getSetFunImpl(class_name, i) << std::endl;
    }

    ofs << std::endl;
    gen_dao_src(ofs);
    ofs << std::endl;

    for (auto it = ns.rbegin(); it != ns.rend(); ++it) {
        ofs << "} //namespace " << *it << std::endl;
    }
}

std::string Table::genToStringInc() {
    std::stringstream ss;
    ss << "std::string toJsonString() const;";
    return ss.str();
}

std::string Table::genToStringSrc(const std::string& class_name) {
    std::stringstream ss;
    ss << "std::string " << GetAsClassName(class_name) << "::toJsonString() const {" << std::endl;
    ss << "    Json::Value v;" << std::endl;
    for (auto it = m_cols.begin(); it != m_cols.end(); ++it) {
        ss << "    v[\"" << (*it)->getName() << "\"] = ";
        if ((*it)->getDType() == Column::TYPE_INT64 || (*it)->getDType() == Column::TYPE_UINT64) {
            ss << "std::to_string(" << GetAsMemberName((*it)->getName()) << ");" << std::endl;
        } else if ((*it)->getDType() == Column::TYPE_TIMESTAMP) {
            ss << "chen::Time2Str(" << GetAsMemberName((*it)->getName()) << ");" << std::endl;
        } else {
            ss << GetAsMemberName((*it)->getName()) << ";" << std::endl;
        }
    }
    ss << "    return chen::JsonUtil::ToString(v);" << std::endl;
    ss << "}" << std::endl;
    return ss.str();
}

std::string Table::getToInsertSQL(const std::string& class_name) {
    std::stringstream ss;
    ss << "std::string " << GetAsClassName(class_name) << "::toInsertSQL() const {" << std::endl;
    ss << "    std::stringstream ss;" << std::endl;
    ss << "    ss << \"insert into " << m_name << "(";
    bool is_first = true;
    for (size_t i = 0; i < m_cols.size(); ++i) {
        if (m_cols[i]->isAutoIncrement()) {
            continue;
        }
        if (!is_first) {
            ss << ",";
        }
        ss << m_cols[i]->getName();
        is_first = false;
    }
    ss << ") values (\"" << std::endl;
    is_first = true;
    for (size_t i = 0; i < m_cols.size(); ++i) {
        if (m_cols[i]->isAutoIncrement()) {
            continue;
        }
        if (!is_first) {
            ss << "    ss << \",\";" << std::endl;
        }
        if (m_cols[i]->getDType() == Column::TYPE_STRING) {
            ss << "    ss << \"'\" << chen::replace(" << GetAsMemberName(m_cols[i]->getName()) << ", \"'\", \"''\") << \"'\";"
               << std::endl;
        } else {
            ss << "    ss << " << GetAsMemberName(m_cols[i]->getName()) << ";" << std::endl;
        }
        is_first = true;
    }
    ss << "    ss << \")\";" << std::endl;
    ss << "    return ss.str();" << std::endl;
    ss << "}" << std::endl;
    return ss.str();
}

std::string Table::getToUpdateSQL(const std::string& class_name) {
    std::stringstream ss;
    ss << "std::string " << GetAsClassName(class_name) << "::toUpdateSQL() const {" << std::endl;
    ss << "    std::stringstream ss;" << std::endl;
    ss << "    bool is_first = true;" << std::endl;
    ss << "    ss << \"update " << m_name << " set \";" << std::endl;
    for (size_t i = 0; i < m_cols.size(); ++i) {
        ss << "    if(_flags & " << (1ul << i) << "ul) {" << std::endl;
        ss << "        if(!is_first) {" << std::endl;
        ss << "            ss << \",\";" << std::endl;
        ss << "        }" << std::endl;
        ss << "        ss << \" " << m_cols[i]->getName() << " = ";
        if (m_cols[i]->getDType() == Column::TYPE_STRING) {
            ss << "'\" << chen::replace(" << GetAsMemberName(m_cols[i]->getName()) << ", \"'\", \"''\") << \"'\";" << std::endl;
        } else {
            ss << "\" << " << GetAsMemberName(m_cols[i]->getName()) << ";" << std::endl;
        }
        ss << "        is_first = false;" << std::endl;
        ss << "    }" << std::endl;
    }
    ss << genWhere();
    ss << "    return ss.str();" << std::endl;
    ss << "}" << std::endl;
    return ss.str();
}

std::string Table::getToDeleteSQL(const std::string& class_name) {
    std::stringstream ss;
    ss << "std::string " << GetAsClassName(class_name) << "::toDeleteSQL() const {" << std::endl;
    ss << "    std::stringstream ss;" << std::endl;
    ss << "    ss << \"delete from " << m_name << "\";" << std::endl;
    ss << genWhere();
    ss << "    return ss.str();" << std::endl;
    ss << "}" << std::endl;
    return ss.str();
}

std::vector<Column::ptr> Table::getPKs() const {
    std::vector<Column::ptr> cols;
    for (auto& i : m_idxs) {
        if (i->isPK()) {
            for (auto& n : i->getCols()) {
                cols.push_back(getCol(n));
            }
        }
    }
    return cols;
}

Column::ptr Table::getCol(const std::string& name) const {
    for (auto& i : m_cols) {
        if (i->getName() == name) {
            return i;
        }
    }
    return nullptr;
}

std::string Table::genWhere() const {
    std::stringstream ss;
    ss << "    ss << \" where ";
    auto pks = getPKs();

    for (size_t i = 0; i < pks.size(); ++i) {
        if (i) {
            ss << "    ss << \" and ";
        }
        ss << pks[i]->getName() << " = ";
        if (pks[i]->getDType() == Column::TYPE_STRING) {
            ss << "'\" << chen::replace(" << GetAsMemberName(m_cols[i]->getName()) << ", \"'\", \"''\") << \"'\";" << std::endl;
        } else {
            ss << "\" << " << GetAsMemberName(m_cols[i]->getName()) << ";" << std::endl;
        }
    }
    return ss.str();
}

template <class V, class T>
bool is_exists(const V& v, const T& t) {
    for (auto& i : v) {
        if (i == t) {
            return true;
        }
    }
    return false;
}

void Table::gen_dao_inc(std::ofstream& ofs) {
    std::string class_name = m_name + m_subfix;
    std::string class_name_dao = class_name + "_dao";
    ofs << "class " << GetAsClassName(class_name_dao) << " {" << std::endl;
    ofs << "public:" << std::endl;
    ofs << "    typedef std::shared_ptr<" << GetAsClassName(class_name_dao) << "> ptr;" << std::endl;
    ofs << "    static int Update(" << GetAsClassName(class_name) << "::ptr info, " << m_updateclass << "::ptr conn);" << std::endl;
    ofs << "    static int Insert(" << GetAsClassName(class_name) << "::ptr info, " << m_updateclass << "::ptr conn);" << std::endl;
    ofs << "    static int InsertOrUpdate(" << GetAsClassName(class_name) << "::ptr info, " << m_updateclass << "::ptr conn);"
        << std::endl;

    // ---- 批量操作 ----
    ofs << "    static int BatchInsert(const std::vector<" << GetAsClassName(class_name) << "::ptr>& infos, "
        << m_updateclass << "::ptr conn);" << std::endl;
    ofs << "    static int BatchUpdate(const std::vector<" << GetAsClassName(class_name) << "::ptr>& infos, "
        << m_updateclass << "::ptr conn);" << std::endl;
    ofs << "    static int BatchDelete(const std::vector<int64_t>& ids, " << m_updateclass << "::ptr conn);" << std::endl;

    ofs << "    static int Delete(" << GetAsClassName(class_name) << "::ptr info, " << m_updateclass << "::ptr conn);" << std::endl;
    auto vs = getPKs();
    ofs << "    static int Delete(";
    for (auto& i : vs) {
        ofs << "const " << i->getDTypeString() << "& " << GetAsVariable(i->getName()) << ", ";
    }
    ofs << m_updateclass << "::ptr conn);" << std::endl;

    for (auto& i : m_idxs) {
        if (i->getDType() == Index::TYPE_UNIQ || i->getDType() == Index::TYPE_PK || i->getDType() == Index::TYPE_INDEX) {
            ofs << "    static int Delete";
            std::string tmp = "by";
            for (auto& c : i->getCols()) {
                tmp += "_" + c;
            }
            ofs << GetAsClassName(tmp) << "(";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << m_updateclass << "::ptr conn);" << std::endl;
        }
    }

    ofs << "    static int QueryAll(std::vector<" << GetAsClassName(class_name) << "::ptr>& results, " << m_queryclass
        << "::ptr conn);" << std::endl;
    ofs << "    static " << GetAsClassName(class_name) << "::ptr Query(";
    for (auto& i : vs) {
        ofs << " const " << i->getDTypeString() << "& " << GetAsVariable(i->getName()) << ", ";
    }
    ofs << m_queryclass << "::ptr conn);" << std::endl;

    for (auto& i : m_idxs) {
        if (i->getDType() == Index::TYPE_UNIQ) {
            ofs << "    static " << GetAsClassName(class_name) << "::ptr Query";
            std::string tmp = "by";
            for (auto& c : i->getCols()) {
                tmp += "_" + c;
            }
            ofs << GetAsClassName(tmp) << "(";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << m_queryclass << "::ptr conn);" << std::endl;
        } else if (i->getDType() == Index::TYPE_INDEX) {
            ofs << "    static int Query";
            std::string tmp = "by";
            for (auto& c : i->getCols()) {
                tmp += "_" + c;
            }
            ofs << GetAsClassName(tmp) << "(";
            ofs << "std::vector<" << GetAsClassName(class_name) << "::ptr>& results, ";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << m_queryclass << "::ptr conn);" << std::endl;

            // Pages variant with COUNT + LIMIT/OFFSET
            ofs << "    static int Query";
            ofs << GetAsClassName(tmp) << "Pages(";
            ofs << "std::vector<" << GetAsClassName(class_name) << "::ptr>& results, int64_t& total, ";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << "int32_t offset, int32_t limit, " << m_queryclass << "::ptr conn);" << std::endl;
        }
    }

    ofs << "    static int CreateTableSQLite3(" << m_dbclass << "::ptr info);" << std::endl;
    ofs << "    static int CreateTableMySQL(" << m_dbclass << "::ptr info);" << std::endl;
    ofs << "    static int MigrateTableSQLite3(" << m_dbclass << "::ptr info);" << std::endl;
    ofs << "    static int MigrateTableMySQL(" << m_dbclass << "::ptr info);" << std::endl;

    // ---- 版本化迁移 ----
    /**
     * @brief 按版本号执行数据库迁移，从当前 DB 版本逐步升级到 XML 定义的版本
     * @param conn 数据库连接
     * @return 0 成功，非 0 失败
     */
    ofs << "    static int Migrate(" << m_dbclass << "::ptr conn);" << std::endl;
    // Generate onMigrate_vN hooks for each version > 1
    for (int v = 2; v <= m_version; ++v) {
        ofs << "    /** @brief v" << v << " 版本迁移钩子，需用户实现具体数据迁移逻辑 */" << std::endl;
        ofs << "    static int onMigrate_v" << v << "(" << m_dbclass << "::ptr conn) { return 0; }" << std::endl;
    }

    // ---- 自定义查询（QueryBuilder） ----

    /**
     * @brief 创建一个预配置表名的 QueryBuilder，用于构建自定义查询
     * @param alias 可选表别名，不为空时生成 "table alias" 格式的表名
     * @return QueryBuilder 实例，表名已设置为当前表
     */
    ofs << "    static chen::QueryBuilder::ptr newQuery(const std::string& alias = \"\");" << std::endl;

    /**
     * @brief 从 ISQLData 当前行解析出一个 Info 对象
     * @param data 结果集（已通过 next() 定位到某一行）
     * @return Info 对象指针
     */
    ofs << "    static " << GetAsClassName(class_name) << "::ptr ParseRow(chen::ISQLData::ptr data);" << std::endl;

    /**
     * @brief 通过 QueryBuilder 执行自定义查询，返回 Info 对象列表
     * @param results 输出结果集
     * @param qb 查询构建器。若未调用过 select()（即仍为默认 "*"），SELECT 列自动设为表的所有列以保证映射正确；
     *           若已设置自定义 SELECT（如 "prs.*"），则保留用户的设置。
     * @param conn 数据库连接
     * @return 0 成功，非 0 失败
     */
    ofs << "    static int QueryByBuilder(std::vector<" << GetAsClassName(class_name) << "::ptr>& results, "
        << "chen::QueryBuilder::ptr qb, " << m_queryclass << "::ptr conn);" << std::endl;

    /**
     * @brief 通过 QueryBuilder 执行分页查询
     * @param results 输出结果集
     * @param total 输出总数
     * @param qb 查询构建器。若未调用过 select()（即仍为默认 "*"），SELECT 列自动设为表的所有列以保证映射正确；
     *           若已设置自定义 SELECT，则保留用户的设置。LIMIT/OFFSET 由参数控制。
     * @param offset 偏移量
     * @param limit 每页数量
     * @param conn 数据库连接
     * @return 0 成功，非 0 失败
     */
    ofs << "    static int QueryByBuilderPages(std::vector<" << GetAsClassName(class_name) << "::ptr>& results, "
        << "int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, "
        << m_queryclass << "::ptr conn);" << std::endl;

    ofs << "};" << std::endl;
}

void Table::gen_dao_src(std::ofstream& ofs) {
    std::string class_name = m_name + m_subfix;
    std::string class_name_dao = class_name + "_dao";
    int idx;
    ofs << "int " << GetAsClassName(class_name_dao) << "::Update(" << GetAsClassName(class_name) << "::ptr info, " << m_updateclass
        << "::ptr conn) {" << std::endl;
    ofs << "    if (!info->isDirty()) {" << std::endl;
    ofs << "        return 0;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    std::string sql = \"update " << m_name << " set \";" << std::endl;
    ofs << "    bool first = true;" << std::endl;
    auto pks = getPKs();
    for (size_t ci = 0; ci < m_cols.size(); ++ci) {
        if (is_exists(pks, m_cols[ci])) continue;
        ofs << "    if (info->m_flags & (1ull << " << ci << ")) {" << std::endl;
        ofs << "        if (!first) sql += \", \";" << std::endl;
        ofs << "        sql += \"" << m_cols[ci]->getName() << " = ?\";" << std::endl;
        ofs << "        first = false;" << std::endl;
        ofs << "    }" << std::endl;
    }
    ofs << "    sql += \" where";
    bool is_first = true;
    for (auto& i : pks) {
        if (!is_first) ofs << " and";
        ofs << " " << i->getName() << " = ?";
        is_first = false;
    }
    ofs << "\";" << std::endl;
#define CHECK_STMT(v)                                                   \
    ofs << "    auto stmt = conn->prepare(sql);" << std::endl;          \
    ofs << "    if(!stmt) {" << std::endl;                              \
    ofs << "        ERROR(logger) << \"stmt=\" << sql" << std::endl     \
        << "            << \" errno=\""                                 \
           " << conn->getErrno() << \" errstr=\" << conn->getErrStr();" \
        << std::endl                                                    \
        << "        return " v ";" << std::endl;                        \
    ofs << "    }" << std::endl;

    CHECK_STMT("conn->getErrno()");
    ofs << "    int idx = 1;" << std::endl;
    for (size_t ci = 0; ci < m_cols.size(); ++ci) {
        if (is_exists(pks, m_cols[ci])) continue;
        ofs << "    if (info->m_flags & (1ull << " << ci << ")) {" << std::endl;
        ofs << "        stmt->" << m_cols[ci]->getBindString() << "(idx++, ";
        ofs << "info->" << GetAsMemberName(m_cols[ci]->getName()) << ");" << std::endl;
        ofs << "    }" << std::endl;
    }
    for (auto& i : pks) {
        ofs << "    stmt->" << i->getBindString() << "(idx++, ";
        ofs << "info->" << GetAsMemberName(i->getName()) << ");" << std::endl;
    }
    ofs << "    int rt = stmt->execute();" << std::endl;
    ofs << "    if (rt == 0) {" << std::endl;
    ofs << "        info->markClean();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return rt;" << std::endl;

    ofs << "}" << std::endl << std::endl;
    ofs << "int " << GetAsClassName(class_name_dao) << "::Insert(" << GetAsClassName(class_name) << "::ptr info, " << m_updateclass
        << "::ptr conn) {" << std::endl;
    ofs << "    std::string sql = \"insert into " << m_name << " (";
    is_first = true;
    Column::ptr auto_inc;

    for (auto& i : m_cols) {
        if (i->isAutoIncrement()) {
            auto_inc = i;
            continue;
        }
        if (!is_first) {
            ofs << ", ";
        }
        ofs << i->getName();
        is_first = false;
    }

    ofs << ") values (";
    is_first = true;
    for (auto& i : m_cols) {
        if (i->isAutoIncrement()) {
            continue;
        }
        if (!is_first) {
            ofs << ", ";
        }
        ofs << "?";
        is_first = false;
    }
    ofs << ")\";" << std::endl;

    CHECK_STMT("conn->getErrno()");

    idx = 1;
    for (auto& i : m_cols) {
        if (i->isAutoIncrement()) {
            continue;
        }
        ofs << "    stmt->" << i->getBindString() << "(" << idx << ", ";
        ofs << "info->" << GetAsMemberName(i->getName());
        ofs << ");" << std::endl;
        ++idx;
    }
    ofs << "    int rt = stmt->execute();" << std::endl;
    if (auto_inc) {
        ofs << "    if(rt == 0) {" << std::endl;
        ofs << "        info->" << GetAsMemberName(auto_inc->getName()) << " = conn->getLastInsertId();" << std::endl
            << "    }" << std::endl;
    }
    ofs << "    if (rt == 0) {" << std::endl;
    ofs << "        info->markClean();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return rt;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    ofs << "int " << GetAsClassName(class_name_dao) << "::InsertOrUpdate(" << GetAsClassName(class_name) << "::ptr info, "
        << m_updateclass << "::ptr conn) {" << std::endl;
    for (auto& i : m_cols) {
        if (i->isAutoIncrement()) {
            auto_inc = i;
            break;
        }
    }
    if (auto_inc) {
        ofs << "    if(info->" << GetAsMemberName(auto_inc->getName()) << " == 0) {" << std::endl;
        ofs << "        return Insert(info, conn);" << std::endl;
        ofs << "    }" << std::endl;
    }
    ofs << "    std::string sql = \"replace into " << m_name << " (";
    is_first = true;
    for (auto& i : m_cols) {
        if (!is_first) {
            ofs << ", ";
        }
        ofs << i->getName();
        is_first = false;
    }

    ofs << ") values (";
    is_first = true;
    for (auto& i : m_cols) {
        (void)i;
        if (!is_first) {
            ofs << ", ";
        }
        ofs << "?";
        is_first = false;
    }
    ofs << ")\";" << std::endl;

    CHECK_STMT("conn->getErrno()");
    idx = 1;
    for (auto& i : m_cols) {
        ofs << "    stmt->" << i->getBindString() << "(" << idx << ", ";
        ofs << "info->" << GetAsMemberName(i->getName()) << ");" << std::endl;
        ++idx;
    }
    ofs << "    int rt = stmt->execute();" << std::endl;
    ofs << "    if (rt == 0) {" << std::endl;
    ofs << "        info->markClean();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return rt;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== BatchInsert =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::BatchInsert(const std::vector<" << GetAsClassName(class_name)
        << "::ptr>& infos, " << m_updateclass << "::ptr conn) {" << std::endl;
    ofs << "    if (infos.empty()) {" << std::endl;
    ofs << "        return 0;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    if (!conn) {" << std::endl;
    ofs << "        ERROR(logger) << \"BatchInsert conn is null\";" << std::endl;
    ofs << "        return -1;" << std::endl;
    ofs << "    }" << std::endl;

    // Build INSERT SQL with multiple value tuples
    ofs << "    std::string sql = \"insert into " << m_name << " (\";" << std::endl;
    is_first = true;
    for (auto& col : m_cols) {
        if (col->isAutoIncrement()) continue;
        if (!is_first) ofs << "    sql += \", \";" << std::endl;
        ofs << "    sql += \"" << col->getName() << "\";" << std::endl;
        is_first = false;
    }
    ofs << "    sql += \") VALUES \";" << std::endl;
    ofs << "    for (size_t r = 0; r < infos.size(); ++r) {" << std::endl;
    ofs << "        if (r) sql += \", \";" << std::endl;
    ofs << "        sql += \"(\";" << std::endl;
    is_first = true;
    for (size_t ci = 0; ci < m_cols.size(); ++ci) {
        if (m_cols[ci]->isAutoIncrement()) continue;
        if (!is_first) ofs << "        sql += \", \";" << std::endl;
        ofs << "        sql += \"?\";" << std::endl;
        is_first = false;
    }
    ofs << "        sql += \")\";" << std::endl;
    ofs << "    }" << std::endl;

    CHECK_STMT("conn->getErrno()");

    // Bind all rows
    ofs << "    int idx = 1;" << std::endl;
    ofs << "    for (auto& info : infos) {" << std::endl;
    for (auto& col : m_cols) {
        if (col->isAutoIncrement()) continue;
        ofs << "        stmt->" << col->getBindString() << "(idx++, info->" << GetAsMemberName(col->getName()) << ");" << std::endl;
    }
    ofs << "    }" << std::endl;
    ofs << "    return stmt->execute();" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== BatchUpdate =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::BatchUpdate(const std::vector<" << GetAsClassName(class_name)
        << "::ptr>& infos, " << m_updateclass << "::ptr conn) {" << std::endl;
    ofs << "    if (infos.empty()) {" << std::endl;
    ofs << "        return 0;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    if (!conn) {" << std::endl;
    ofs << "        ERROR(logger) << \"BatchUpdate conn is null\";" << std::endl;
    ofs << "        return -1;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    auto trans = conn->openTransaction(true);" << std::endl;
    ofs << "    if (!trans || !trans->begin()) {" << std::endl;
    ofs << "        ERROR(logger) << \"BatchUpdate begin transaction failed\";" << std::endl;
    ofs << "        return -1;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    for (auto& info : infos) {" << std::endl;
    ofs << "        if (Update(info, conn)) {" << std::endl;
    ofs << "            ERROR(logger) << \"BatchUpdate Update failed\";" << std::endl;
    ofs << "            trans->rollback();" << std::endl;
    ofs << "            return conn->getErrno();" << std::endl;
    ofs << "        }" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    trans->commit();" << std::endl;
    ofs << "    return 0;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== BatchDelete =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::BatchDelete(const std::vector<int64_t>& ids, "
        << m_updateclass << "::ptr conn) {" << std::endl;
    ofs << "    if (ids.empty()) {" << std::endl;
    ofs << "        return 0;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    if (!conn) {" << std::endl;
    ofs << "        ERROR(logger) << \"BatchDelete conn is null\";" << std::endl;
    ofs << "        return -1;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    std::string sql = \"delete from " << m_name << " where ";
    {
        auto pks = getPKs();
        is_first = true;
        for (auto& pk : pks) {
            if (!is_first) ofs << " and ";
            ofs << pk->getName();
            is_first = false;
        }
    }
    ofs << " IN (\";" << std::endl;
    ofs << "    for (size_t i = 0; i < ids.size(); ++i) {" << std::endl;
    ofs << "        if (i) sql += \", \";" << std::endl;
    ofs << "        sql += \"?\";" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    sql += \")\";" << std::endl;
    CHECK_STMT("conn->getErrno()");
    ofs << "    int idx = 1;" << std::endl;
    ofs << "    for (auto& id : ids) {" << std::endl;
    ofs << "        stmt->bindInt64(idx++, id);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return stmt->execute();" << std::endl;
    ofs << "}" << std::endl << std::endl;

    ofs << "int " << GetAsClassName(class_name_dao) << "::Delete(" << GetAsClassName(class_name) << "::ptr info, " << m_updateclass
        << "::ptr conn) {" << std::endl;

    ofs << "    std::string sql = \"delete from " << m_name << " where";
    is_first = true;
    for (auto& i : pks) {
        if (!is_first) {
            ofs << " and";
        }
        ofs << " " << i->getName() << " = ?";
        is_first = false;
    }
    ofs << "\";" << std::endl;
    CHECK_STMT("conn->getErrno()");
    idx = 1;
    for (auto& i : pks) {
        ofs << "    stmt->" << i->getBindString() << "(" << idx << ", ";
        ofs << "info->" << GetAsMemberName(i->getName()) << ");" << std::endl;
        ++idx;
    }
    ofs << "    return stmt->execute();" << std::endl;
    ofs << "}" << std::endl << std::endl;

    for (auto& i : m_idxs) {
        if (i->getDType() == Index::TYPE_UNIQ || i->getDType() == Index::TYPE_PK || i->getDType() == Index::TYPE_INDEX) {
            ofs << "int " << GetAsClassName(class_name_dao) << "::Delete";
            std::string tmp = "by";
            for (auto& c : i->getCols()) {
                tmp += "_" + c;
            }
            ofs << GetAsClassName(tmp) << "(";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << m_updateclass << "::ptr conn) {" << std::endl;
            ofs << "    std::string sql = \"delete from " << m_name << " where";
            is_first = true;
            for (auto& x : i->getCols()) {
                if (!is_first) {
                    ofs << " and";
                }
                ofs << " " << x << " = ?";
                is_first = false;
            }
            ofs << "\";" << std::endl;
            CHECK_STMT("conn->getErrno()");
            idx = 1;
            for (auto& x : i->getCols()) {
                ofs << "    stmt->" << getCol(x)->getBindString() << "(" << idx << ", ";
                ofs << GetAsVariable(x) << ");" << std::endl;
            }
            ofs << "    return stmt->execute();" << std::endl;
            ofs << "}" << std::endl << std::endl;
        }
    }

    ofs << "int " << GetAsClassName(class_name_dao) << "::QueryAll(std::vector<" << GetAsClassName(class_name) << "::ptr>& results, "
        << m_queryclass << "::ptr conn) {" << std::endl;
    ofs << "    std::string sql = \"select ";
    is_first = true;
    for (auto& i : m_cols) {
        if (!is_first) {
            ofs << ", ";
        }
        ofs << i->getName();
        is_first = false;
    }
    ofs << " from " << m_name << "\";" << std::endl;
    CHECK_STMT("conn->getErrno()");
    ofs << "    auto rt = stmt->query();" << std::endl;
    ofs << "    if(!rt) {" << std::endl;
    ofs << "        return stmt->getErrno();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    while (rt->next()) {" << std::endl;
    ofs << "        " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;

#define PARSE_OBJECT(prefix)                                                           \
    for (size_t i = 0; i < m_cols.size(); ++i) {                                       \
        ofs << prefix "v->" << GetAsMemberName(m_cols[i]->getName()) << " = ";         \
        ofs << "rt->" << m_cols[i]->getGetString() << "(" << (i) << ");" << std::endl; \
    }
    PARSE_OBJECT("        ");
    ofs << "        results.push_back(v);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return 0;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    ofs << GetAsClassName(class_name) << "::ptr " << GetAsClassName(class_name_dao) << "::Query(";
    for (auto& i : pks) {
        ofs << " const " << i->getDTypeString() << "& " << GetAsVariable(i->getName()) << ", ";
    }
    ofs << m_queryclass << "::ptr conn) {" << std::endl;

    ofs << "    std::string sql = \"select ";
    is_first = true;
    for (auto& i : m_cols) {
        if (!is_first) {
            ofs << ", ";
        }
        ofs << i->getName();
        is_first = false;
    }
    ofs << " from " << m_name << " where";
    is_first = true;
    for (auto& i : pks) {
        if (!is_first) {
            ofs << " and";
        }
        ofs << " " << i->getName() << " = ?";
        is_first = false;
    }
    ofs << "\";" << std::endl;

    CHECK_STMT("nullptr");
    idx = 1;
    for (auto& i : pks) {
        ofs << "    stmt->" << i->getBindString() << "(" << idx << ", ";
        ofs << GetAsVariable(i->getName()) << ");" << std::endl;
        ++idx;
    }
    ofs << "    auto rt = stmt->query();" << std::endl;
    ofs << "    if(!rt) {" << std::endl;
    ofs << "        return nullptr;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    if(!rt->next()) {" << std::endl;
    ofs << "        return nullptr;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;
    PARSE_OBJECT("    ");
    ofs << "    return v;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    for (auto& i : m_idxs) {
        if (i->getDType() == Index::TYPE_UNIQ) {
            ofs << "" << GetAsClassName(class_name) << "::ptr " << GetAsClassName(class_name_dao) << "::Query";
            std::string tmp = "by";
            for (auto& c : i->getCols()) {
                tmp += "_" + c;
            }
            ofs << GetAsClassName(tmp) << "(";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << m_queryclass << "::ptr conn) {" << std::endl;

            ofs << "    std::string sql = \"select ";
            is_first = true;
            for (auto& i : m_cols) {
                if (!is_first) {
                    ofs << ", ";
                }
                ofs << i->getName();
                is_first = false;
            }
            ofs << " from " << m_name << " where";
            is_first = true;
            for (auto& x : i->getCols()) {
                if (!is_first) {
                    ofs << " and";
                }
                ofs << " " << x << " = ?";
                is_first = false;
            }
            ofs << "\";" << std::endl;
            CHECK_STMT("nullptr");

            idx = 1;
            for (auto& x : i->getCols()) {
                ofs << "    stmt->" << getCol(x)->getBindString() << "(" << idx << ", ";
                ofs << GetAsVariable(x) << ");" << std::endl;
                ++idx;
            }
            ofs << "    auto rt = stmt->query();" << std::endl;
            ofs << "    if(!rt) {" << std::endl;
            ofs << "        return nullptr;" << std::endl;
            ofs << "    }" << std::endl;
            ofs << "    if(!rt->next()) {" << std::endl;
            ofs << "        return nullptr;" << std::endl;
            ofs << "    }" << std::endl;
            ofs << "    " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;
            PARSE_OBJECT("    ");
            ofs << "    return v;" << std::endl;
            ofs << "}" << std::endl << std::endl;
        } else if (i->getDType() == Index::TYPE_INDEX) {
            ofs << "int " << GetAsClassName(class_name_dao) << "::Query";
            std::string tmp = "by";
            for (auto& c : i->getCols()) {
                tmp += "_" + c;
            }
            ofs << GetAsClassName(tmp) << "(";
            ofs << "std::vector<" << GetAsClassName(class_name) << "::ptr>& results, ";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << m_queryclass << "::ptr conn) {" << std::endl;

            ofs << "    std::string sql = \"select ";
            is_first = true;
            for (auto& i : m_cols) {
                if (!is_first) {
                    ofs << ", ";
                }
                ofs << i->getName();
                is_first = false;
            }
            ofs << " from " << m_name << " where";
            is_first = true;
            for (auto& x : i->getCols()) {
                if (!is_first) {
                    ofs << " and";
                }
                ofs << " " << x << " = ?";
                is_first = false;
            }
            ofs << "\";" << std::endl;
            CHECK_STMT("conn->getErrno()");

            idx = 1;
            for (auto& x : i->getCols()) {
                ofs << "    stmt->" << getCol(x)->getBindString() << "(" << idx << ", ";
                ofs << GetAsVariable(x) << ");" << std::endl;
                ++idx;
            }
            ofs << "    auto rt = stmt->query();" << std::endl;
            ofs << "    if(!rt) {" << std::endl;
            ofs << "        return 0;" << std::endl;
            ofs << "    }" << std::endl;
            ofs << "    while (rt->next()) {" << std::endl;
            ofs << "        " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;
            PARSE_OBJECT("        ");
            ofs << "        results.push_back(v);" << std::endl;
            ofs << "    };" << std::endl;
            ofs << "    return 0;" << std::endl;
            ofs << "}" << std::endl << std::endl;

            // Pages variant with COUNT + LIMIT/OFFSET
            ofs << "int " << GetAsClassName(class_name_dao) << "::Query";
            ofs << GetAsClassName(tmp) << "Pages(";
            ofs << "std::vector<" << GetAsClassName(class_name) << "::ptr>& results, int64_t& total, ";
            for (auto& c : i->getCols()) {
                auto d = getCol(c);
                ofs << " const " << d->getDTypeString() << "& " << GetAsVariable(d->getName()) << ", ";
            }
            ofs << "int32_t offset, int32_t limit, " << m_queryclass << "::ptr conn) {" << std::endl;

            // COUNT query
            ofs << "    std::string countSql = \"select count(*) from " << m_name << " where";
            is_first = true;
            for (auto& x : i->getCols()) {
                if (!is_first) {
                    ofs << " and";
                }
                ofs << " " << x << " = ?";
                is_first = false;
            }
            ofs << "\";" << std::endl;
            ofs << "    auto countStmt = conn->prepare(countSql);" << std::endl;
            ofs << "    if (!countStmt) {" << std::endl;
            ofs << "        ERROR(logger) << \"stmt=\" << countSql" << std::endl
                << "                 << \" errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
            ofs << "        return conn->getErrno();" << std::endl;
            ofs << "    }" << std::endl;
            idx = 1;
            for (auto& x : i->getCols()) {
                ofs << "    countStmt->" << getCol(x)->getBindString() << "(" << idx << ", ";
                ofs << GetAsVariable(x) << ");" << std::endl;
                ++idx;
            }
            ofs << "    auto countRt = countStmt->query();" << std::endl;
            ofs << "    if (!countRt) {" << std::endl;
            ofs << "        return countStmt->getErrno();" << std::endl;
            ofs << "    }" << std::endl;
            ofs << "    if (countRt->next()) {" << std::endl;
            ofs << "        total = countRt->getInt64(0);" << std::endl;
            ofs << "    }" << std::endl;
            ofs << "    if (total == 0) {" << std::endl;
            ofs << "        return 0;" << std::endl;
            ofs << "    }" << std::endl;

            // SELECT query with pagination
            ofs << "    std::string sql = \"select ";
            is_first = true;
            for (auto& col : m_cols) {
                if (!is_first) {
                    ofs << ", ";
                }
                ofs << col->getName();
                is_first = false;
            }
            ofs << " from " << m_name << " where";
            is_first = true;
            for (auto& x : i->getCols()) {
                if (!is_first) {
                    ofs << " and";
                }
                ofs << " " << x << " = ?";
                is_first = false;
            }
            ofs << " order by ";
            {
                auto pks = getPKs();
                is_first = true;
                for (auto& pk : pks) {
                    if (!is_first) {
                        ofs << ", ";
                    }
                    ofs << pk->getName() << " desc";
                    is_first = false;
                }
            }
            ofs << " limit ? offset ?\";" << std::endl;
            CHECK_STMT("conn->getErrno()");

            idx = 1;
            for (auto& x : i->getCols()) {
                ofs << "    stmt->" << getCol(x)->getBindString() << "(" << idx << ", ";
                ofs << GetAsVariable(x) << ");" << std::endl;
                ++idx;
            }
            ofs << "    stmt->bindInt32(" << idx << ", limit);" << std::endl;
            ++idx;
            ofs << "    stmt->bindInt32(" << idx << ", offset);" << std::endl;
            ofs << "    auto rt = stmt->query();" << std::endl;
            ofs << "    if (!rt) {" << std::endl;
            ofs << "        return 0;" << std::endl;
            ofs << "    }" << std::endl;
            ofs << "    while (rt->next()) {" << std::endl;
            ofs << "        " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;
            PARSE_OBJECT("        ");
            ofs << "        results.push_back(v);" << std::endl;
            ofs << "    };" << std::endl;
            ofs << "    return 0;" << std::endl;
            ofs << "}" << std::endl << std::endl;
        }
    }

    // ===== ParseRow (从 ISQLData 当前行构造 Info 对象) =====
    ofs << GetAsClassName(class_name) << "::ptr " << GetAsClassName(class_name_dao) << "::ParseRow(chen::ISQLData::ptr data) {" << std::endl;
    ofs << "    if (!data) {" << std::endl;
    ofs << "        ERROR(logger) << \"ParseRow data is null\";" << std::endl;
    ofs << "        return nullptr;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;
    for (size_t i = 0; i < m_cols.size(); ++i) {
        ofs << "    v->" << GetAsMemberName(m_cols[i]->getName()) << " = ";
        ofs << "data->" << m_cols[i]->getGetString() << "(" << i << ");" << std::endl;
    }
    ofs << "    return v;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== newQuery (创建预配置表名的 QueryBuilder) =====
    ofs << "chen::QueryBuilder::ptr " << GetAsClassName(class_name_dao) << "::newQuery(const std::string& alias) {" << std::endl;
    ofs << "    std::string table = \"" << m_name << "\";" << std::endl;
    ofs << "    if (!alias.empty()) {" << std::endl;
    ofs << "        table += \" \" + alias;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return chen::QueryBuilder::Create(table);" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== QueryByBuilder (通过 QueryBuilder 执行自定义查询) =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::QueryByBuilder(std::vector<" << GetAsClassName(class_name) << "::ptr>& results, "
        << "chen::QueryBuilder::ptr qb, " << m_queryclass << "::ptr conn) {" << std::endl;
    ofs << "    if (!qb || !conn) {" << std::endl;
    ofs << "        ERROR(logger) << \"QueryByBuilder qb or conn is null\";" << std::endl;
    ofs << "        return -1;" << std::endl;
    ofs << "    }" << std::endl;

    // Build column list — if user set a custom SELECT (e.g. "prs.*" for JOINs), keep it
    ofs << "    std::string sql;" << std::endl;
    ofs << "    if (qb->getSelectCols() != \"*\") {" << std::endl;
    ofs << "        sql = qb->buildQuerySQL();" << std::endl;
    ofs << "    } else {" << std::endl;
    ofs << "        sql = qb->buildQuerySQL(\"";
    is_first = true;
    for (auto& i : m_cols) {
        if (!is_first) {
            ofs << ", ";
        }
        ofs << i->getName();
        is_first = false;
    }
    ofs << "\");" << std::endl;
    ofs << "    }" << std::endl;

    CHECK_STMT("conn->getErrno()");
    ofs << "    qb->bindParams(stmt);" << std::endl;
    ofs << "    auto rt = stmt->query();" << std::endl;
    ofs << "    if(!rt) {" << std::endl;
    ofs << "        return stmt->getErrno();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    while (rt->next()) {" << std::endl;
    ofs << "        " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;
    PARSE_OBJECT("        ");
    ofs << "        results.push_back(v);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return 0;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== QueryByBuilderPages (分页自定义查询) =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::QueryByBuilderPages(std::vector<" << GetAsClassName(class_name) << "::ptr>& results, "
        << "int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, "
        << m_queryclass << "::ptr conn) {" << std::endl;
    ofs << "    if (!qb || !conn) {" << std::endl;
    ofs << "        ERROR(logger) << \"QueryByBuilderPages qb or conn is null\";" << std::endl;
    ofs << "        return -1;" << std::endl;
    ofs << "    }" << std::endl;

    // COUNT query
    ofs << "    std::string countSql = qb->buildCountSQL();" << std::endl;
    ofs << "    auto countStmt = conn->prepare(countSql);" << std::endl;
    ofs << "    if (!countStmt) {" << std::endl;
    ofs << "        ERROR(logger) << \"stmt=\" << countSql" << std::endl
        << "            << \" errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
    ofs << "        return conn->getErrno();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    qb->bindQueryParams(countStmt);" << std::endl;
    ofs << "    auto countRt = countStmt->query();" << std::endl;
    ofs << "    if (!countRt) {" << std::endl;
    ofs << "        return countStmt->getErrno();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    if (countRt->next()) {" << std::endl;
    ofs << "        total = countRt->getInt64(0);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    if (total == 0) {" << std::endl;
    ofs << "        return 0;" << std::endl;
    ofs << "    }" << std::endl;

    // Build data SQL without LIMIT/OFFSET (qb's ORDER BY is preserved)
    // If user set a custom SELECT, use it; otherwise use full table column list
    ofs << "    std::string sql;" << std::endl;
    ofs << "    if (qb->getSelectCols() != \"*\") {" << std::endl;
    ofs << "        sql = qb->buildQuerySQL(qb->getSelectCols(), false);" << std::endl;
    ofs << "    } else {" << std::endl;
    ofs << "        sql = qb->buildQuerySQL(\"";
    is_first = true;
    for (auto& i : m_cols) {
        if (!is_first) {
            ofs << ", ";
        }
        ofs << i->getName();
        is_first = false;
    }
    ofs << "\", false);" << std::endl;
    ofs << "    }" << std::endl;

    // Add default ORDER BY if qb doesn't have one
    ofs << "    if (!qb->hasOrderBy()) {" << std::endl;
    ofs << "        sql += \" order by ";
    {
        auto pks = getPKs();
        is_first = true;
        for (auto& pk : pks) {
            if (!is_first) {
                ofs << ", ";
            }
            ofs << pk->getName() << " desc";
            is_first = false;
        }
    }
    ofs << "\";" << std::endl;
    ofs << "    }" << std::endl;

    // Add custom LIMIT/OFFSET
    ofs << "    sql += \" limit ? offset ?\";" << std::endl;

    CHECK_STMT("conn->getErrno()");

    // Bind WHERE + HAVING params from qb, then LIMIT + OFFSET
    ofs << "    qb->bindQueryParams(stmt);" << std::endl;
    ofs << "    int idx = qb->getQueryParamCount() + 1;" << std::endl;
    ofs << "    stmt->bindInt32(idx++, limit);" << std::endl;
    ofs << "    stmt->bindInt32(idx++, offset);" << std::endl;

    ofs << "    auto rt = stmt->query();" << std::endl;
    ofs << "    if (!rt) {" << std::endl;
    ofs << "        return 0;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    while (rt->next()) {" << std::endl;
    ofs << "        " << GetAsClassName(class_name) << "::ptr v(new " << GetAsClassName(class_name) << ");" << std::endl;
    PARSE_OBJECT("        ");
    ofs << "        results.push_back(v);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return 0;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    ofs << "int " << GetAsClassName(class_name_dao) << "::CreateTableSQLite3(" << m_dbclass << "::ptr conn) {" << std::endl;
    ofs << "    return conn->execute(\"CREATE TABLE IF NOT EXISTS " << m_name << "(\"" << std::endl;
    is_first = true;
    bool has_auto_increment = false;
    for (auto& i : m_cols) {
        if (!is_first) {
            ofs << ",\"" << std::endl;
        }
        ofs << "            \"" << i->getName() << " " << i->getSQLite3TypeString();
        if (i->isAutoIncrement()) {
            ofs << " PRIMARY KEY AUTOINCREMENT";
            has_auto_increment = true;
        } else {
            ofs << " NOT NULL DEFAULT " << i->getSQLite3Default();
        }
        is_first = false;
    }
    if (!has_auto_increment) {
        ofs << ", PRIMARY KEY(";
        is_first = true;
        for (auto& i : pks) {
            if (!is_first) {
                ofs << ", ";
            }
            ofs << i->getName();
        }
        ofs << ")";
    }
    ofs << ");\"" << std::endl;
    for (auto& i : m_idxs) {
        if (i->getDType() == Index::TYPE_PK) {
            continue;
        }
        ofs << "            \"CREATE";
        if (i->getDType() == Index::TYPE_UNIQ) {
            ofs << " UNIQUE";
        }
        ofs << " INDEX IF NOT EXISTS " << m_name;
        for (auto& x : i->getCols()) {
            ofs << "_" << x;
        }
        ofs << " ON " << m_name << "(";
        is_first = true;
        for (auto& x : i->getCols()) {
            if (!is_first) {
                ofs << ",";
            }
            ofs << x;
            is_first = false;
        }
        ofs << ");\"" << std::endl;
    }
    ofs << "            );" << std::endl;
    ofs << "}" << std::endl << std::endl;

    ofs << "int " << GetAsClassName(class_name_dao) << "::CreateTableMySQL(" << m_dbclass << "::ptr conn) {" << std::endl;
    ofs << "    return conn->execute(\"CREATE TABLE IF NOT EXISTS " << m_name << "(\"" << std::endl;
    is_first = true;
    for (auto& i : m_cols) {
        if (!is_first) {
            ofs << ",\"" << std::endl;
        }
        ofs << "            \"`" << i->getName() << "` " << i->getMySQLTypeString();
        if (i->isAutoIncrement()) {
            ofs << " AUTO_INCREMENT";
            has_auto_increment = true;
        } else {
            ofs << " NOT NULL";
            if (i->getDType() != Column::TYPE_TEXT && i->getDType() != Column::TYPE_BLOB) {
                ofs << " DEFAULT " << i->getSQLite3Default();
            }
        }

        if (!i->getUpdate().empty()) {
            ofs << " ON UPDATE " << i->getUpdate() << " ";
        }
        if (!i->getDesc().empty()) {
            ofs << " COMMENT '" << i->getDesc() << "'";
        }
        is_first = false;
    }
    ofs << ",\"" << std::endl << "            \"PRIMARY KEY(";
    is_first = true;
    for (auto& i : pks) {
        if (!is_first) {
            ofs << ", ";
        }
        ofs << "`" << i->getName() << "`";
    }
    ofs << ")";
    for (auto& i : m_idxs) {
        if (i->getDType() == Index::TYPE_PK) {
            continue;
        }
        ofs << ",\"" << std::endl;
        if (i->getDType() == Index::TYPE_UNIQ) {
            ofs << "            \"UNIQUE ";
        } else {
            ofs << "            \"";
        }
        ofs << "KEY `" << m_name;
        for (auto& x : i->getCols()) {
            ofs << "_" << x;
        }
        ofs << "` (";
        is_first = true;
        for (auto& x : i->getCols()) {
            if (!is_first) {
                ofs << ",";
            }
            ofs << "`" << x << "`";
            is_first = false;
        }
        ofs << ")";
    }
    ofs << ")";
    if (!m_desc.empty()) {
        ofs << " COMMENT='" << m_desc << "'";
    }
    ofs << "\");" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== Migrate (版本化迁移) =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::Migrate(" << m_dbclass << "::ptr conn) {" << std::endl;
    ofs << "    if (!conn) {" << std::endl;
    ofs << "        ERROR(logger) << \"Migrate conn is null\";" << std::endl;
    ofs << "        return -1;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << std::endl;
    // Create schema_version table
    ofs << "    conn->execute(\"CREATE TABLE IF NOT EXISTS schema_version (\"\n"
        << "        \"table_name VARCHAR(128) PRIMARY KEY, \"\n"
        << "        \"version INT NOT NULL DEFAULT 0)\");" << std::endl;
    ofs << std::endl;
    // Read current DB version
    ofs << "    auto verStmt = conn->prepare(\"SELECT version FROM schema_version WHERE table_name = ?\");" << std::endl;
    ofs << "    if (!verStmt) {" << std::endl;
    ofs << "        ERROR(logger) << \"Migrate prepare version query failed errno=\" << conn->getErrno();" << std::endl;
    ofs << "        return conn->getErrno();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    verStmt->bindString(1, \"" << m_name << "\");" << std::endl;
    ofs << "    auto verRt = verStmt->query();" << std::endl;
    ofs << "    int dbVer = 0;" << std::endl;
    ofs << "    if (verRt && verRt->next()) {" << std::endl;
    ofs << "        dbVer = (int)verRt->getInt64(0);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << std::endl;

    // Generate migration chain for each version
    for (int v = 1; v <= m_version; ++v) {
        ofs << "    if (dbVer < " << v << ") {" << std::endl;
        if (v == 1) {
            if (m_dbType == DB_MYSQL) {
                ofs << "        if (CreateTableMySQL(conn)) {" << std::endl;
            } else {
                ofs << "        if (CreateTableSQLite3(conn)) {" << std::endl;
            }
            ofs << "            ERROR(logger) << \"Migrate v1 CreateTable failed\";" << std::endl;
            ofs << "            return conn->getErrno();" << std::endl;
            ofs << "        }" << std::endl;
        } else {
            if (m_dbType == DB_MYSQL) {
                ofs << "        if (MigrateTableMySQL(conn)) {" << std::endl;
            } else {
                ofs << "        if (MigrateTableSQLite3(conn)) {" << std::endl;
            }
            ofs << "            ERROR(logger) << \"Migrate v" << v << " DDL failed\";" << std::endl;
            ofs << "            return conn->getErrno();" << std::endl;
            ofs << "        }" << std::endl;
        }
        if (v >= 2) {
            ofs << "        if (onMigrate_v" << v << "(conn)) {" << std::endl;
            ofs << "            ERROR(logger) << \"Migrate v" << v << " data migration failed\";" << std::endl;
            ofs << "            return conn->getErrno();" << std::endl;
            ofs << "        }" << std::endl;
        }
        ofs << "    }" << std::endl;
        ofs << std::endl;
    }

    // Update schema version
    ofs << "    if (dbVer == 0) {" << std::endl;
    ofs << "        auto insStmt = conn->prepare(\"INSERT INTO schema_version (table_name, version) VALUES (?, ?)\");" << std::endl;
    ofs << "        if (insStmt) {" << std::endl;
    ofs << "            insStmt->bindString(1, \"" << m_name << "\");" << std::endl;
    ofs << "            insStmt->bindInt32(2, " << m_version << ");" << std::endl;
    ofs << "            insStmt->execute();" << std::endl;
    ofs << "        }" << std::endl;
    ofs << "    } else {" << std::endl;
    ofs << "        auto updStmt = conn->prepare(\"UPDATE schema_version SET version = ? WHERE table_name = ?\");" << std::endl;
    ofs << "        if (updStmt) {" << std::endl;
    ofs << "            updStmt->bindInt32(1, " << m_version << ");" << std::endl;
    ofs << "            updStmt->bindString(2, \"" << m_name << "\");" << std::endl;
    ofs << "            updStmt->execute();" << std::endl;
    ofs << "        }" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    return 0;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    gen_dao_migrate_src(ofs);
}

void Table::gen_dao_migrate_src(std::ofstream& ofs) {
    std::string class_name = m_name + m_subfix;
    std::string class_name_dao = class_name + "_dao";

    // ===== SQLite3 Migration =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::MigrateTableSQLite3(" << m_dbclass << "::ptr conn) {" << std::endl;
    ofs << "    auto data = conn->query(\"PRAGMA table_info(" << m_name << ")\");" << std::endl;
    ofs << "    if (!data) {" << std::endl;
    ofs << "        ERROR(logger) << \"PRAGMA table_info(" << m_name
        << ") errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
    ofs << "        return conn->getErrno();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    std::map<std::string, std::string> existing_cols;  // name -> type" << std::endl;
    ofs << "    while (data->next()) {" << std::endl;
    ofs << "        existing_cols[data->getString(1)] = data->getString(2);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << std::endl;

    // Check if any existing column has a different type (requires table recreate)
    ofs << "    bool need_recreate = false;" << std::endl;
    for (auto& col : m_cols) {
        ofs << "    {" << std::endl;
        ofs << "        auto it = existing_cols.find(\"" << col->getName() << "\");" << std::endl;
        ofs << "        if (it != existing_cols.end() && it->second != \"" << col->getSQLite3TypeString() << "\") {" << std::endl;
        ofs << "            INFO(logger) << \"Column type changed: " << m_name << "." << col->getName()
            << " \" << it->second << \" -> " << col->getSQLite3TypeString() << "\";" << std::endl;
        ofs << "            need_recreate = true;" << std::endl;
        ofs << "        }" << std::endl;
        ofs << "    }" << std::endl;
    }
    // Also check for extra columns (exist in DB but not in XML)
    ofs << "    if (!need_recreate) {" << std::endl;
    ofs << "        for (auto& [name, _] : existing_cols) {" << std::endl;
    ofs << "            (void)_;  // suppress unused warning" << std::endl;
    ofs << "            bool found = false;" << std::endl;
    for (auto& col : m_cols) {
        ofs << "            if (name == \"" << col->getName() << "\") found = true;" << std::endl;
    }
    ofs << "            if (!found) {" << std::endl;
    ofs << "                need_recreate = true;" << std::endl;
    ofs << "                WARN(logger) << \"Column " << m_name << ".\" << name << \" removed, table recreate required\";"
        << std::endl;
    ofs << "                break;" << std::endl;
    ofs << "            }" << std::endl;
    ofs << "        }" << std::endl;
    ofs << "    }" << std::endl;
    ofs << std::endl;

    // ===== Recreate path: any type change or column removal =====
    ofs << "    if (need_recreate) {" << std::endl;
    ofs << "        INFO(logger) << \"Recreating table " << m_name << "\";" << std::endl;
    ofs << std::endl;

    // Collect common columns between old and new schemas
    ofs << "        std::vector<std::string> common_cols;" << std::endl;
    for (auto& col : m_cols) {
        ofs << "        if (existing_cols.find(\"" << col->getName() << "\") != existing_cols.end()) {" << std::endl;
        ofs << "            common_cols.push_back(\"" << col->getName() << "\");" << std::endl;
        ofs << "        }" << std::endl;
    }
    ofs << std::endl;

    // Recreate: rename old → create new → copy data → drop old
    ofs << "        if (conn->execute(\"ALTER TABLE " << m_name << " RENAME TO " << m_name << "_tmp\")) {" << std::endl;
    ofs << "            ERROR(logger) << \"RENAME TABLE " << m_name << " failed\";" << std::endl;
    ofs << "            return conn->getErrno();" << std::endl;
    ofs << "        }" << std::endl;
    ofs << "        CreateTableSQLite3(conn);" << std::endl;

    // INSERT INTO x (cols...) SELECT cols... FROM x_tmp
    ofs << "        if (!common_cols.empty()) {" << std::endl;
    ofs << "            std::string cols;" << std::endl;
    ofs << "            for (size_t i = 0; i < common_cols.size(); ++i) {" << std::endl;
    ofs << "                if (i) cols += \",\";" << std::endl;
    ofs << "                cols += common_cols[i];" << std::endl;
    ofs << "            }" << std::endl;
    ofs << "            std::string sql = \"INSERT INTO " << m_name << " (\" + cols + \") SELECT \" + cols + \" FROM " << m_name
        << "_tmp\";" << std::endl;
    ofs << "            if (int rt = conn->execute(sql)) {" << std::endl;
    ofs << "                ERROR(logger) << \"copy data from " << m_name << "_tmp to " << m_name << " failed, errno=\" << rt;"
        << std::endl;
    ofs << "                // don't return; try to continue" << std::endl;
    ofs << "            }" << std::endl;
    ofs << "        }" << std::endl;
    ofs << "        conn->execute(\"DROP TABLE " << m_name << "_tmp\");" << std::endl;
    ofs << "        return 0;" << std::endl;
    ofs << "    }" << std::endl;
    ofs << std::endl;

    // ===== Lightweight path: ADD/DROP only =====
    // Add missing columns
    for (auto& col : m_cols) {
        if (col->isAutoIncrement()) {
            continue;
        }
        ofs << "    if (existing_cols.find(\"" << col->getName() << "\") == existing_cols.end()) {" << std::endl;
        ofs << "        INFO(logger) << \"Adding column " << m_name << "." << col->getName() << "\";" << std::endl;
        ofs << "        int rt = conn->execute(\"ALTER TABLE " << m_name << " ADD COLUMN " << col->getName() << " "
            << col->getSQLite3TypeString() << " NOT NULL DEFAULT " << col->getSQLite3Default() << "\");" << std::endl;
        ofs << "        if (rt) {" << std::endl;
        ofs << "            ERROR(logger) << \"ALTER TABLE " << m_name << " ADD COLUMN " << col->getName()
            << " failed, errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
        ofs << "        }" << std::endl;
        ofs << "    }" << std::endl;
        ofs << std::endl;
    }

    ofs << "    return 0;" << std::endl;
    ofs << "}" << std::endl << std::endl;

    // ===== MySQL Migration (uses native MODIFY COLUMN / DROP COLUMN, no recreate) =====
    ofs << "int " << GetAsClassName(class_name_dao) << "::MigrateTableMySQL(" << m_dbclass << "::ptr conn) {" << std::endl;
    ofs << "    auto data = conn->query(\"SHOW COLUMNS FROM " << m_name << "\");" << std::endl;
    ofs << "    if (!data) {" << std::endl;
    ofs << "        ERROR(logger) << \"SHOW COLUMNS FROM " << m_name
        << " errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
    ofs << "        return conn->getErrno();" << std::endl;
    ofs << "    }" << std::endl;
    ofs << "    std::map<std::string, std::string> existing_cols;  // name -> type" << std::endl;
    ofs << "    while (data->next()) {" << std::endl;
    ofs << "        existing_cols[data->getString(0)] = data->getString(1);" << std::endl;
    ofs << "    }" << std::endl;
    ofs << std::endl;

    // Modify columns whose type has changed
    for (auto& col : m_cols) {
        ofs << "    {" << std::endl;
        ofs << "        auto it = existing_cols.find(\"" << col->getName() << "\");" << std::endl;
        ofs << "        if (it != existing_cols.end() && it->second != \"" << col->getMySQLTypeString() << "\") {" << std::endl;
        ofs << "            INFO(logger) << \"Modifying column " << m_name << "." << col->getName() << " \" << it->second << \" -> "
            << col->getMySQLTypeString() << "\";" << std::endl;
        ofs << "            int rt = conn->execute(\"ALTER TABLE " << m_name << " MODIFY COLUMN `" << col->getName() << "` "
            << col->getMySQLTypeString() << " NOT NULL";
        if (col->getDType() != Column::TYPE_TEXT && col->getDType() != Column::TYPE_BLOB) {
            ofs << " DEFAULT " << col->getSQLite3Default();
        }
        if (!col->getDesc().empty()) {
            ofs << " COMMENT '" << col->getDesc() << "'";
        }
        ofs << "\");" << std::endl;
        ofs << "            if (rt) {" << std::endl;
        ofs << "                ERROR(logger) << \"MODIFY COLUMN " << m_name << "." << col->getName()
            << " failed, errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
        ofs << "            }" << std::endl;
        ofs << "        }" << std::endl;
        ofs << "    }" << std::endl;
    }
    ofs << std::endl;

    // Drop columns that exist in DB but not in XML
    ofs << "    for (auto& [name, _] : existing_cols) {" << std::endl;
    ofs << "        (void)_;" << std::endl;
    ofs << "        bool found = false;" << std::endl;
    for (auto& col : m_cols) {
        ofs << "        if (name == \"" << col->getName() << "\") found = true;" << std::endl;
    }
    ofs << "        if (!found) {" << std::endl;
    ofs << "            WARN(logger) << \"Dropping column " << m_name << ".\" << name << \" (not in schema, data will be lost)\";"
        << std::endl;
    ofs << "            int rt = conn->execute(\"ALTER TABLE " << m_name << " DROP COLUMN `\" + name + \"`\");" << std::endl;
    ofs << "            if (rt) {" << std::endl;
    ofs << "                ERROR(logger) << \"DROP COLUMN " << m_name
        << ".\" << name << \" failed, errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
    ofs << "            }" << std::endl;
    ofs << "        }" << std::endl;
    ofs << "    }" << std::endl;
    ofs << std::endl;

    // Add missing columns (in XML but not in DB)
    for (auto& col : m_cols) {
        if (col->isAutoIncrement()) {
            continue;
        }
        ofs << "    if (existing_cols.find(\"" << col->getName() << "\") == existing_cols.end()) {" << std::endl;
        ofs << "        INFO(logger) << \"Adding column " << m_name << "." << col->getName() << "\";" << std::endl;
        ofs << "        int rt = conn->execute(\"ALTER TABLE " << m_name << " ADD COLUMN `" << col->getName() << "` "
            << col->getMySQLTypeString();
        if (col->getDType() != Column::TYPE_TEXT && col->getDType() != Column::TYPE_BLOB) {
            ofs << " NOT NULL DEFAULT " << col->getSQLite3Default();
        }
        if (!col->getDesc().empty()) {
            ofs << " COMMENT '" << col->getDesc() << "'";
        }
        ofs << "\");" << std::endl;
        ofs << "        if (rt) {" << std::endl;
        ofs << "            ERROR(logger) << \"ALTER TABLE " << m_name << " ADD COLUMN " << col->getName()
            << " failed, errno=\" << conn->getErrno() << \" errstr=\" << conn->getErrStr();" << std::endl;
        ofs << "        }" << std::endl;
        ofs << "    }" << std::endl;
        ofs << std::endl;
    }

    ofs << "    return 0;" << std::endl;
    ofs << "}" << std::endl << std::endl;
}

} // namespace orm
} // namespace chen
